version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_CERTIFICATE_DIR}:/etc/certs
    ports:
      - 443:443
    depends_on:
      - gonito
  gonito:
    image: loxygen/gonito
    depends_on:
      - postgres
    environment:
      - PGUSER=postgres
      - PGPASS=$POSTGRES_PASSWORD
      - PGHOST=postgres
      - ADMINUSER=$GONITO_ADMINUSER
      - ADMINPASS=$GONITO_ADMINPASS
      - LOCATION=$GONITO_LOCATION
      - APPROOT=$GONITO_APPROOT
      - LEADERBOARD_STYLE=${GONITO_LEADERBOARD_STYLE:-by-tag}
      - AUTO_OPENING=${GONITO_AUTO_OPENING:-false}
      - IS_PUBLIC=${GONITO_IS_PUBLIC:-true}
    expose:
      - "3000"
    volumes:
      - "${GONITO_ARENA_VOLUME}:/gonito/arena"
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=gonito
    expose:
      - "5432"
    volumes:
      - "${PG_DATA_VOLUME}:/var/lib/postgresql/data"
