flags:
  gonito:
    library-only: false
    dev: false
packages:
- '.'
- '../geval'
extra-deps: [markdown-0.1.13.2,geval-0.3.2.0,cond-0.4.1.1,wai-handler-fastcgi-3.0.0.2,murmur3-1.0.3,extra-1.4.10]
resolver: lts-6.24
