flags:
  gonito:
    library-only: false
    dev: false
packages:
- '.'
- location:
    git: https://github.com/bitemyapp/esqueleto
    commit: b81e0d951e510ebffca03c5a58658ad884cc6fbd
  extra-dep: true
extra-deps: [../geval,wai-handler-fastcgi-3.0.0.2,murmur3-1.0.3,random-strings-0.1.1.0,naturalcomp-0.0.3]
resolver: lts-11.9
image:
  container:
    name: filipg/gonito
    base: fpco/stack-run
    add:
        executables: /usr/local/bin/gonito-bin
