flags:
  gonito:
    library-only: false
    dev: false
packages:
- '.'
- '../geval'
extra-deps: [markdown-0.1.13.2,geval-0.2.3.0,cond-0.4.1.1]
compiler-check: newer-minor
resolver: nightly-2015-12-19
