# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:      "_env:STATIC_DIR:static"
host:            "_env:HOST:*4" # any IPv4 host
port:            "_env:PORT:3000"
approot:         "_env:APPROOT:http://localhost:3000"
ip-from-header:  "_env:IP_FROM_HEADER:false"
var-dir:         "_env:VAR_DIR:."
contact-email:   "_env:CONTACT_EMAIL:filipg@amu.edu.pl"
repo-host:       "_env:REPO_HOST:ssh://gitolite@gonito.net/"
repo-scheme:     "_env:REPO_SCHEME:selfhosted"
tag-permissions: "_env:TAG_PERMISSIONS:only-admin-can-add-new-tags"
auto-opening:    "_env:AUTO_OPENING:false"
leaderboard-style: "_env:LEADERBOARD_STYLE:by-submitter"
new-best-result-slack-hook: "_env:NEW_BEST_RESULT_SLACK_HOOK:"
server-ssh-public-key: "_env:SERVER_SSH_PUBLIC_KEY:"
is-public:    "_env:IS_PUBLIC:true"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  user:     "_env:PGUSER:filipg"
  password: "_env:PGPASS:gonito"
  host:     "_env:PGHOST:localhost"
  port:     "_env:PGPORT:5432"
  database: "_env:PGDATABASE:gonito"
  poolsize: "_env:PGPOOLSIZE:10"

copyright: © Filip Graliński

admin-user: "_env:ADMINUSER:"
admin-password: "_env:ADMINPASS:"
location: "_env:LOCATION:"

#analytics: UA-YOURCODE
